spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 960406
    driver-class-name: com.mysql.cj.jdbc.Driver

  #运行时显示sql语句，格式化输出
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181